# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 984f6c2aef1731aae0dd8fd773dd11ab70acdf9d36e7e3587d0f9c92c7122e1426e09ee6fa67361b6f7449a4b9b494be9f4483072437e6d7f736fbe78ec8160c

test:
  secret_key_base: 0a923cf4846b4bdb3c2f713b6971de5d2459aa53b6164f38e65b0173936c891482756fa0e040d29e562f49ca38e9d97b19887b2ffd9dc0fc8537535bbf0011b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
